enum Token {
    RESERVED_KEYWORD = 1,
    SYMBOL,
    CLASS_STEREOTYPE,
    CLASS_ID,
    RELATION_STEREOTYPE,
    RELATION_ID,
    INSTANCE_ID,
    NATIVE_DT,
    CUSTOM_DT,
    META_ATTRIBUTE,
    INVALID
};
